/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.awt.Font;
import ui.StudentForm;
import ui.LabRecordForm;
import ui.LoginFrame;


/**
 *
 * @author saura
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    public void loadUsers() {

    try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM users WHERE status='PENDING'";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
                (DefaultTableModel) tblUsers.getModel();

        model.setRowCount(0);

        while(rs.next()) {

            model.addRow(new Object[] {

                rs.getInt("id"),
                rs.getString("fullname"),
                rs.getString("username"),
                rs.getString("email"),
                rs.getString("role"),
                rs.getString("status")

            });

        }

    } catch(Exception e) {

        System.out.println(e);

    }

}

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadUsers();
        setTitle("Admin Dashboard");
        getContentPane().setBackground(new Color(44, 62, 80));

    jLabel2.setForeground(Color.WHITE);

    jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 20));
             getContentPane().setBackground(new Color(44, 62, 80));

// APPROVE BUTTON
btnApprove.setBackground(new Color(46, 204, 113));
btnApprove.setForeground(Color.WHITE);
btnApprove.setFocusPainted(false);
btnApprove.setBorderPainted(false);
btnApprove.setContentAreaFilled(false);
btnApprove.setOpaque(true);

// REJECT BUTTON
btnReject.setBackground(new Color(231, 76, 60));
btnReject.setForeground(Color.WHITE);
btnReject.setFocusPainted(false);
btnReject.setBorderPainted(false);
btnReject.setContentAreaFilled(false);
btnReject.setOpaque(true);

// TABLE DESIGN
tblUsers.setRowHeight(30);


tblUsers.getTableHeader().setFont(
        new Font("Segoe UI", Font.BOLD, 14));

tblUsers.getTableHeader().setBackground(
        new Color(52, 73, 94));

tblUsers.getTableHeader().setForeground(Color.WHITE);
tblUsers.getTableHeader().setOpaque(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnLabRecord = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ADMIN DASHBOARD - PENDING USERS");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Username", "Email", "Role", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btnApprove.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnApprove.setText("APPROVE");
        btnApprove.addActionListener(this::btnApproveActionPerformed);

        btnReject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReject.setText("REJECT");
        btnReject.addActionListener(this::btnRejectActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudent.setText("STUDENT MANAGEMENT");
        btnStudent.addActionListener(this::btnStudentActionPerformed);

        btnLabRecord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLabRecord.setText("LAB RECORD MANAGEMENT");
        btnLabRecord.addActionListener(this::btnLabRecordActionPerformed);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLabRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStudent)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(jButton1)
                    .addComponent(btnLabRecord))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReject)
                            .addComponent(btnStudent))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
     

    try {

        int row = tblUsers.getSelectedRow();

        if(row == -1) {

            JOptionPane.showMessageDialog(this,
                    "Select User First");

            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Reject this user?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );

        if(confirm != JOptionPane.YES_OPTION) {
            return;
        }

        int id = Integer.parseInt(
                tblUsers.getValueAt(row, 0).toString());

        String sql =
                "UPDATE users SET status='REJECTED' WHERE id=?";

        try (
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(sql)
        ) {

            pst.setInt(1, id);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "User Rejected");

            loadUsers();

        }

    } catch(Exception e) {

        e.printStackTrace();

    }

        
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        try {

    int row = tblUsers.getSelectedRow();

    if(row == -1) {

        JOptionPane.showMessageDialog(this,
                "Select User First");

        return;
    }

    int id = Integer.parseInt(
            tblUsers.getValueAt(row, 0).toString());

    Connection con = DBConnection.getConnection();

    String sql =
            "UPDATE users SET status='APPROVED' WHERE id=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setInt(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(this,
            "User Approved Successfully");

    loadUsers();

} catch(Exception e) {

    System.out.println(e);

}
    }//GEN-LAST:event_btnApproveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        new StudentForm().setVisible(true);
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnLabRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabRecordActionPerformed
        // TODO add your handling code here:
        new LabRecordForm().setVisible(true);
          this.dispose();
                      
    }//GEN-LAST:event_btnLabRecordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(AdminDashboard.
        this,
        "Are you sure you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
);

if(confirm == JOptionPane.YES_OPTION) {

    new LoginFrame().setVisible(true);

    this.dispose();

}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
    try {

        javax.swing.UIManager.setLookAndFeel(
            javax.swing.UIManager.getCrossPlatformLookAndFeelClassName()
        );

    } catch (Exception ex) {

        logger.log(java.util.logging.Level.SEVERE, null, ex);

    }

    java.awt.EventQueue.invokeLater(() -> {
        new AdminDashboard().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnLabRecord;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
