/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author saura
 */
public class LabRecordForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LabRecordForm.class.getName());
    public void loadRecords() {

    try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM lab_records";

        PreparedStatement pst =
                con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
                (DefaultTableModel) tblRecords.getModel();

        model.setRowCount(0);

        while(rs.next()) {

            model.addRow(new Object[] {

                rs.getInt("record_id"),
                rs.getString("roll_no"),
                rs.getString("student_name"),
                rs.getString("experiment_name"),
                rs.getString("submission_status"),
                rs.getString("marks")

            });

        }

    } catch(Exception e) {

       e.printStackTrace();
JOptionPane.showMessageDialog(this, e.getMessage());

    }

}

    /**
     * Creates new form LabRecordForm
     */
    public LabRecordForm() {
        initComponents();
            loadRecords();
            tblRecords.setRowHeight(25);
tblRecords.setFont(new Font("Arial", Font.PLAIN, 14));
tblRecords.setRowHeight(25);

javax.swing.table.JTableHeader header =
        tblRecords.getTableHeader();

header.setFont(new Font("Arial", Font.BOLD, 14));

header.setPreferredSize(new Dimension(100, 30));

tblRecords.setGridColor(Color.LIGHT_GRAY);
tblRecords.setShowGrid(true);
tblRecords.setBackground(Color.WHITE);
tblRecords.setForeground(Color.BLACK);
tblRecords.getTableHeader().setFont(
        new Font("Arial", Font.BOLD, 14));

getContentPane().setBackground(
        new Color(220,240,255));

btnAdd.setBackground(new Color(46, 204, 113));
btnAdd.setForeground(Color.WHITE);

btnUpdate.setBackground(new Color(52, 152, 219));
btnUpdate.setForeground(Color.WHITE);

btnDelete.setBackground(new Color(231, 76, 60));
btnDelete.setForeground(Color.WHITE);

btnSearch.setBackground(new Color(243, 156, 18));
btnSearch.setForeground(Color.WHITE);

btnClear.setBackground(new Color(127, 140, 141));
btnClear.setForeground(Color.WHITE);

jButton1.setBackground(new Color(155, 89, 182));
jButton1.setForeground(Color.WHITE);
javax.swing.JButton[] buttons = {
    btnAdd,
    btnUpdate,
    btnDelete,
    btnSearch,
    btnClear,
    jButton1
};

for(javax.swing.JButton btn : buttons) {

    btn.setOpaque(true);

    btn.setBorderPainted(false);

    btn.setFocusPainted(false);

    btn.setContentAreaFilled(true);

    btn.setFont(new Font("Segoe UI", Font.BOLD, 14));
}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRollNo = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtMarks = new javax.swing.JTextField();
        txtExperimentName = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRecords = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText(" Roll No:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Student Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Experiment Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Submission Status:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Marks:");

        txtExperimentName.addActionListener(this::txtExperimentNameActionPerformed);

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Submitted", "Pending" }));
        cmbStatus.addActionListener(this::cmbStatusActionPerformed);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(this::btnClearActionPerformed);

        tblRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Roll No", "Student Name", "Experiment", "Status", "Marks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRecords);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("LAB RECORD MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRollNo, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                                            .addComponent(txtExperimentName)
                                            .addComponent(txtMarks)
                                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUpdate)
                                            .addComponent(btnClear))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(btnDelete)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(510, 510, 510)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRollNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtExperimentName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear)
                    .addComponent(jButton1))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtExperimentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperimentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperimentNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
    Integer.parseInt(txtMarks.getText());
}catch(Exception e){
    JOptionPane.showMessageDialog(this,
            "Marks must be number");
    return;
}
         if(cmbStatus.getSelectedIndex() == 0){

    JOptionPane.showMessageDialog(
            LabRecordForm.this,
            "Please select Status");
            return;
         }
         if(txtRollNo.getText().isEmpty() ||
   txtStudentName.getText().isEmpty() ||
   txtExperimentName.getText().isEmpty() ||
   txtMarks.getText().isEmpty()){

    JOptionPane.showMessageDialog(LabRecordForm.this,
            "Please fill all fields");
    return;
}
        try {

    Connection con = DBConnection.getConnection();

    String sql =
            "INSERT INTO lab_records(roll_no,student_name,experiment_name,submission_status,marks) VALUES(?,?,?,?,?)";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setString(1, txtRollNo.getText());
    pst.setString(2, txtStudentName.getText());
    pst.setString(3, txtExperimentName.getText());
    pst.setString(4,
            cmbStatus.getSelectedItem().toString());
    pst.setString(5, txtMarks.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(LabRecordForm.this,
            "Lab Record Added");

    loadRecords();
    btnClearActionPerformed(null);

} catch(Exception e) {

    e.printStackTrace();
JOptionPane.showMessageDialog(LabRecordForm.this, e.getMessage());

}
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            txtRollNo.setText("");
            txtStudentName.setText("");
            txtExperimentName.setText("");
            txtMarks.setText("");
            cmbStatus.setSelectedIndex(0);
            tblRecords.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecordsMouseClicked
        // TODO add your handling code here:
        int row = tblRecords.getSelectedRow();

txtRollNo.setText(
        tblRecords.getValueAt(row,1).toString());

txtStudentName.setText(
        tblRecords.getValueAt(row,2).toString());

txtExperimentName.setText(
        tblRecords.getValueAt(row,3).toString());

cmbStatus.setSelectedItem(
        tblRecords.getValueAt(row,4).toString());

txtMarks.setText(
        tblRecords.getValueAt(row,5).toString());
    }//GEN-LAST:event_tblRecordsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       
    int row = tblRecords.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(LabRecordForm.this,
                "Please select a row");
        return;
    }

    try {

        int id = Integer.parseInt(
                tblRecords.getValueAt(row,0).toString());

        Connection con = DBConnection.getConnection();

        String sql =
                "UPDATE lab_records SET roll_no=?,student_name=?,experiment_name=?,submission_status=?,marks=? WHERE record_id=?";

        PreparedStatement pst =
                con.prepareStatement(sql);

        pst.setString(1, txtRollNo.getText());
        pst.setString(2, txtStudentName.getText());
        pst.setString(3, txtExperimentName.getText());
        pst.setString(4,
                cmbStatus.getSelectedItem().toString());
        pst.setString(5, txtMarks.getText());

        pst.setInt(6, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(LabRecordForm.this,
                "Record Updated");

        loadRecords();
        btnClearActionPerformed(null);

    } catch(Exception e) {

        e.printStackTrace();
        JOptionPane.showMessageDialog(LabRecordForm.this,
                e.getMessage());

    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        

    int row = tblRecords.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(LabRecordForm.this,
                "Please select a row");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(LabRecordForm.
            this,
            "Are you sure to delete?",
            "Confirm",
            JOptionPane.YES_NO_OPTION);

    if(confirm != JOptionPane.YES_OPTION){
        return;
    }

    try {

        int id = Integer.parseInt(
                tblRecords.getValueAt(row,0).toString());

        Connection con = DBConnection.getConnection();

        String sql =
                "DELETE FROM lab_records WHERE record_id=?";

        PreparedStatement pst =
                con.prepareStatement(sql);

        pst.setInt(1, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(LabRecordForm.this,
                "Record Deleted");

        loadRecords();

    } catch(Exception e) {

        e.printStackTrace();
        JOptionPane.showMessageDialog(LabRecordForm.this,
                e.getMessage());

    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try {

    Connection con = DBConnection.getConnection();

    String sql =
            "SELECT * FROM lab_records WHERE roll_no=?";

    PreparedStatement pst =
            con.prepareStatement(sql);

    pst.setString(1, txtRollNo.getText());

    ResultSet rs = pst.executeQuery();

    DefaultTableModel model =
            (DefaultTableModel) tblRecords.getModel();

    model.setRowCount(0);

    while(rs.next()) {

        model.addRow(new Object[] {

            rs.getInt("record_id"),
            rs.getString("roll_no"),
            rs.getString("student_name"),
            rs.getString("experiment_name"),
            rs.getString("submission_status"),
            rs.getString("marks")

        });

    }

} catch(Exception e) {

     e.printStackTrace();
JOptionPane.showMessageDialog(LabRecordForm.this, e.getMessage());

}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdminDashboard().setVisible(true);
        this.dispose();
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LabRecordForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblRecords;
    private javax.swing.JTextField txtExperimentName;
    private javax.swing.JTextField txtMarks;
    private javax.swing.JTextField txtRollNo;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
